/**
 * Invoice Templates Master Configurations and Definitions
 * Supports 10 distinct Indian GST and multi-purpose invoice template themes.
 */

export const INVOICE_TEMPLATES = [
  {
    id: "classic_gst",
    alias: "Classic",
    name: "Classic GST",
    subtitle: "Official Indian Standard",
    category: "GST",
    tags: ["GST", "Standard", "Wholesale"],
    description: "Official government-standard GST tax invoice with full HSN/SAC breakdown, tax slabs, and legal terms.",
    primaryColor: "#1e3a8a",
    secondaryColor: "#475569",
    accentColor: "#f59e0b",
    fontFamily: "Inter",
    headerLayout: "standard",
    tableStyle: "bordered",
    borderStyle: "solid",
    recommendedPaper: "A4",
    badgeText: "Recommended for GST",
    badgeColor: "bg-blue-100 text-blue-800 border-blue-200",
  },
  {
    id: "modern_blue",
    alias: "Modern",
    name: "Modern Blue",
    subtitle: "Clean SaaS Aesthetic",
    category: "Modern",
    tags: ["Modern", "GST", "Retail"],
    description: "Contemporary SaaS-style layout with solid colored header banner, clear accents, and rounded summary cards.",
    primaryColor: "#2563eb",
    secondaryColor: "#64748b",
    accentColor: "#3b82f6",
    fontFamily: "Inter",
    headerLayout: "banner",
    tableStyle: "modern_filled",
    borderStyle: "subtle",
    recommendedPaper: "A4",
    badgeText: "Most Popular",
    badgeColor: "bg-emerald-100 text-emerald-800 border-emerald-200",
  },
  {
    id: "minimal_clean",
    alias: "Minimal",
    name: "Minimal Clean",
    subtitle: "High Whitespace & Elegance",
    category: "Minimal",
    tags: ["Minimal", "Modern"],
    description: "Subtle lines, high whitespace, typography-first aesthetic with refined monochrome accents.",
    primaryColor: "#0f172a",
    secondaryColor: "#64748b",
    accentColor: "#94a3b8",
    fontFamily: "Inter",
    headerLayout: "minimal",
    tableStyle: "minimal",
    borderStyle: "clean",
    recommendedPaper: "A4",
    badgeText: "Ultra Light",
    badgeColor: "bg-slate-100 text-slate-800 border-slate-200",
  },
  {
    id: "corporate",
    alias: "Corporate",
    name: "Corporate Elite",
    subtitle: "Executive Dual Column",
    category: "Modern",
    tags: ["Modern", "GST", "Wholesale"],
    description: "Formal dual-column corporate design with deep executive slate and gold accents, ideal for enterprise billing.",
    primaryColor: "#0f2744",
    secondaryColor: "#475569",
    accentColor: "#d97706",
    fontFamily: "Outfit",
    headerLayout: "split",
    tableStyle: "bordered",
    borderStyle: "solid",
    recommendedPaper: "A4",
    badgeText: "Enterprise",
    badgeColor: "bg-indigo-100 text-indigo-800 border-indigo-200",
  },
  {
    id: "retail",
    alias: "Retail",
    name: "Retail Express",
    subtitle: "High Speed POS Billing",
    category: "Retail",
    tags: ["Retail", "Standard"],
    description: "Designed for retail POS and supermarkets, emphasizing customer savings, payment mode, and quick scan.",
    primaryColor: "#059669",
    secondaryColor: "#64748b",
    accentColor: "#10b981",
    fontFamily: "Inter",
    headerLayout: "standard",
    tableStyle: "striped",
    borderStyle: "subtle",
    recommendedPaper: "A4",
    badgeText: "Fast Billing",
    badgeColor: "bg-emerald-100 text-emerald-800 border-emerald-200",
  },
  {
    id: "wholesale",
    alias: "Wholesale",
    name: "Wholesale Pro",
    subtitle: "B2B Bulk Distribution",
    category: "Wholesale",
    tags: ["Wholesale", "GST"],
    description: "Built for B2B distributors & wholesalers with bulk quantity columns, packaging units, and multi-tax matrix.",
    primaryColor: "#4f46e5",
    secondaryColor: "#64748b",
    accentColor: "#f59e0b",
    fontFamily: "Roboto",
    headerLayout: "split",
    tableStyle: "bordered",
    borderStyle: "solid",
    recommendedPaper: "A4",
    badgeText: "B2B Ready",
    badgeColor: "bg-amber-100 text-amber-800 border-amber-200",
  },
  {
    id: "elegant",
    alias: "Elegant",
    name: "Elegant Luxury",
    subtitle: "Boutique & Premium Styling",
    category: "Minimal",
    tags: ["Minimal", "Retail", "Modern"],
    description: "Boutique, luxury, and salon invoice layout with warm champagne borders, serif headings, and refined touches.",
    primaryColor: "#831843",
    secondaryColor: "#701a75",
    accentColor: "#b45309",
    fontFamily: "Playfair Display",
    headerLayout: "centered",
    tableStyle: "minimal",
    borderStyle: "clean",
    recommendedPaper: "A4",
    badgeText: "Luxury Tier",
    badgeColor: "bg-rose-100 text-rose-800 border-rose-200",
  },
  {
    id: "compact_thermal",
    alias: "Thermal",
    name: "Compact Thermal",
    subtitle: "80mm / 58mm POS Roll",
    category: "Thermal",
    tags: ["Thermal", "Retail"],
    description: "Optimized 80mm/58mm continuous roll receipt layout with dotted dividers and crisp monospace totals.",
    primaryColor: "#18181b",
    secondaryColor: "#52525b",
    accentColor: "#000000",
    fontFamily: "Fira Code",
    headerLayout: "centered",
    tableStyle: "minimal",
    borderStyle: "clean",
    recommendedPaper: "Thermal 80mm",
    badgeText: "POS Roll Print",
    badgeColor: "bg-zinc-200 text-zinc-800 border-zinc-300",
  },
  {
    id: "professional_dark",
    alias: "Dark",
    name: "Professional Dark",
    subtitle: "Slate Contrast & Tech",
    category: "Modern",
    tags: ["Modern", "GST"],
    description: "Sleek dark themed header and high-contrast tables for agencies, tech firms, and digital studios.",
    primaryColor: "#1e293b",
    secondaryColor: "#475569",
    accentColor: "#0284c7",
    fontFamily: "Inter",
    headerLayout: "banner",
    tableStyle: "modern_filled",
    borderStyle: "solid",
    recommendedPaper: "A4",
    badgeText: "Dark Accent",
    badgeColor: "bg-slate-800 text-slate-100 border-slate-700",
  },
  {
    id: "creative_gradient",
    alias: "Gradient",
    name: "Creative Gradient",
    subtitle: "Vibrant Digital Gradient",
    category: "Modern",
    tags: ["Modern", "Retail"],
    description: "Eye-catching mesh gradient header banner, dynamic cards, and colorful grand total highlights.",
    primaryColor: "#7c3aed",
    secondaryColor: "#2563eb",
    accentColor: "#ec4899",
    fontFamily: "Poppins",
    headerLayout: "banner",
    tableStyle: "modern_filled",
    borderStyle: "subtle",
    recommendedPaper: "A4",
    badgeText: "Creative Style",
    badgeColor: "bg-purple-100 text-purple-800 border-purple-200",
  },
];

export const TEMPLATE_CATEGORIES = [
  { key: "all", label: "All Templates" },
  { key: "GST", label: "GST Tax Invoices" },
  { key: "Retail", label: "Retail & POS" },
  { key: "Wholesale", label: "Wholesale & B2B" },
  { key: "Minimal", label: "Minimal & Clean" },
  { key: "Modern", label: "Modern & Creative" },
  { key: "Thermal", label: "Thermal Receipt" },
];

export const FONT_FAMILIES = [
  { id: "Inter", name: "Inter (Modern Clean Sans)", css: "'Inter', sans-serif" },
  { id: "Outfit", name: "Outfit (Geometric Contemporary)", css: "'Outfit', sans-serif" },
  { id: "Roboto", name: "Roboto (Industrial Standard)", css: "'Roboto', sans-serif" },
  { id: "Poppins", name: "Poppins (Rounded Geometric)", css: "'Poppins', sans-serif" },
  { id: "Playfair Display", name: "Playfair (Classic Serif)", css: "'Playfair Display', serif" },
  { id: "Fira Code", name: "Fira Code (Monospace Technical)", css: "'Fira Code', monospace" },
];

export const COLOR_PRESETS = [
  { name: "Royal Blue", primary: "#2563eb", secondary: "#64748b", accent: "#3b82f6" },
  { name: "Navy Classic", primary: "#1e3a8a", secondary: "#475569", accent: "#f59e0b" },
  { name: "Emerald Pro", primary: "#059669", secondary: "#64748b", accent: "#10b981" },
  { name: "Indigo Corporate", primary: "#4f46e5", secondary: "#64748b", accent: "#f59e0b" },
  { name: "Executive Slate", primary: "#0f2744", secondary: "#475569", accent: "#d97706" },
  { name: "Dark Velvet", primary: "#831843", secondary: "#701a75", accent: "#b45309" },
  { name: "Carbon Minimal", primary: "#0f172a", secondary: "#64748b", accent: "#94a3b8" },
  { name: "Electric Purple", primary: "#7c3aed", secondary: "#2563eb", accent: "#ec4899" },
  { name: "Crimson Red", primary: "#dc2626", secondary: "#64748b", accent: "#ea580c" },
  { name: "Teal Modern", primary: "#0d9488", secondary: "#64748b", accent: "#06b6d4" },
];

export function getTemplateConfig(templateId) {
  if (!templateId) return INVOICE_TEMPLATES[0];
  const normalized = String(templateId).toLowerCase().trim();
  const match = INVOICE_TEMPLATES.find(
    (t) =>
      t.id.toLowerCase() === normalized ||
      t.alias.toLowerCase() === normalized ||
      t.name.toLowerCase() === normalized
  );
  return match || INVOICE_TEMPLATES[0];
}

export default INVOICE_TEMPLATES;
